services:
  db:
    image: postgres:16
    container_name: chatbot_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chat_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: chatbot_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/chat_db

  frontend:
    build: ./frontend
    container_name: chatbot_frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend


volumes:
  pgdata: