version: '3.9'

services:
  db:
    image: postgres:16
    container_name: chatbot_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: chatbot_app
    ports:
      - "8501:8501"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata: